[59]:.. Bindings for reuseaddr
roc-streaming/roc-go pull request #63
Opened 2023-03-21 10:26 UTC by Darrellbor

PR for #59 
Implemented:
- [x] binding for `roc_receiver_set_reuseaddr`
- [x] binding for `roc_sender_set_reuseaddr`
- [x] test for `sender.SetReuseaddr()`
- [x] test for `receiver.SetReuseaddr()`

2023-03-22 06:26 UTC, ortex requested changes

2023-03-22 06:26 UTC, ortex commented on roc/sender_receiver_test.go
> +func TestSenderSetReuseaddr(t *testing.T) {
I think it's better to move this test to sender_test

2023-03-22 12:49 UTC, Darrellbor commented
pushed the fixes, although the tests stopped, can you restart it

2023-03-22 15:41 UTC, gavv reviewed
Thanks for PR! A few comments from me too

2023-03-22 18:44 UTC, gavv commented
BTW when request is ready for (re-)review, please leave a comment or press "request review" button to indicate that - otherwise it's hard to guess whether it's already time to look at the pushed changes.

2023-03-22 21:26 UTC, Darrellbor commented
Noted @gavv

2023-03-23 11:30 UTC, gavv commented
Thanks for update!

+1 from me.

@ortex

2023-03-23 11:30 UTC, gavv approved these changes

2023-03-23 11:36 UTC, ortex approved these changes

2023-03-23 11:36 UTC, ortex commented
LGTM

2023-03-23 12:37 UTC, Darrellbor commented on roc/receiver_test.go
> +			name:                 "Ok",
test-case name fixed

2023-03-23 12:46 UTC, merged

2023-03-23 12:46 UTC, gavv commented
Thank you!